# Generated by Django 3.2.5 on 2021-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(max_length=800)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Invitees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=10)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('point', models.IntegerField(default=0)),
                ('answer_1', models.IntegerField(default=0)),
                ('answer_2', models.IntegerField(default=0)),
                ('answer_3', models.IntegerField(default=0)),
                ('answer_4', models.IntegerField(default=0)),
                ('answer_5', models.IntegerField(default=0)),
                ('answer_6', models.IntegerField(default=0)),
                ('answer_7', models.IntegerField(default=0)),
                ('answer_8', models.IntegerField(default=0)),
                ('answer_9', models.IntegerField(default=0)),
                ('answer_10', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(default='', max_length=10)),
                ('quiz_category', models.CharField(default='', max_length=10)),
                ('quiz_text', models.TextField(default='', max_length=400)),
                ('quiz_correct', models.IntegerField(default=0)),
                ('correct_text', models.CharField(default='', max_length=100)),
                ('explanation', models.TextField(default='', max_length=600)),
                ('choice_1', models.CharField(default='', max_length=100)),
                ('choice_2', models.CharField(default='', max_length=100)),
                ('choice_3', models.CharField(default='', max_length=100)),
                ('choice_4', models.CharField(default='', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
