# Generated by Django 3.2.5 on 2021-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210911_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choices_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices_4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
