# Generated by Django 3.2.5 on 2021-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210912_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(default='', max_length=10),
        ),
    ]
