# Generated by Django 3.2.5 on 2021-09-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quiz_quiz_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='choices_1',
            new_name='choice_1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choices_2',
            new_name='choice_2',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choices_3',
            new_name='choice_3',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='choices_4',
            new_name='choice_4',
        ),
    ]
