# Generated by Django 3.2.5 on 2021-09-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20210918_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(max_length=800)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_text',
            field=models.TextField(default='', max_length=400),
        ),
    ]
