# Generated by Django 3.2.5 on 2021-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(default='', max_length=600),
        ),
    ]
